info:
  author: huss
  date: 20222年10月27号
  remark: spring groovy 测试
  my-server-name: spring-groovy-test

server:
  port: 8083

#spring
spring:
  application:
    name: ${info.my-server-name}
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true