server:
  port: 8085
  session-timeout: 30
  servlet:
    context-path: /liteflow
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
spring:
  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: true
    proxy-target-class: true
  http:
    encoding:
      enable: true
  redis:
    host: 192.168.29.66
    port: 6379
    database: 12
    password: zhyx_redis
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000
    cache:
      #缓存的名称集合，多个采用逗号分割
      cache-names:
      #缓存的类型，官方提供了很多，这里我们填写redis
      type: redis
      redis:
        #是否缓存null数据，默认是false
        cache-null-values: false
        #redis中缓存超时的时间，默认60000ms
        time-to-live: 60000ms
        #缓存数据key是否使用前缀，默认是true
        use-key-prefix: false
        #缓存数据key的前缀，在上面的配置为true时有效
        key-prefix:

# liteflow配置
liteflow:
  #规则文件路径
  rule-source: flow/*.el.xml
  #-----------------以下非必须-----------------
  #liteflow是否开启，默认为true
  enable: true
  #liteflow的banner打印是否开启，默认为true
  print-banner: true
  #zkNode的节点，只有使用zk作为配置源的时候才起作用，默认为/lite-flow/flow
  zk-node: /lite-flow/flow
  #上下文的最大数量槽，默认值为1024
  slot-size: 1024
  #FlowExecutor的execute2Future的线程数，默认为64
  main-executor-works: 64
  #FlowExecutor的execute2Future的自定义线程池Builder，LiteFlow提供了默认的Builder
  main-executor-class: com.yomahub.liteflow.thread.LiteFlowDefaultMainExecutorBuilder
  #自定义请求ID的生成类，LiteFlow提供了默认的生成类
  request-id-generator-class: com.yomahub.liteflow.flow.id.DefaultRequestIdGenerator
  #并行节点的线程池Builder，LiteFlow提供了默认的Builder
  thread-executor-class: com.yomahub.liteflow.thread.LiteFlowDefaultWhenExecutorBuilder
  #异步线程最长的等待时间秒(只用于when)，默认值为15
  when-max-wait-seconds: 15
  #when节点全局异步线程池最大线程数，默认为16
  when-max-workers: 16
  #when节点全局异步线程池等待队列数，默认为512
  when-queue-limit: 512
  #是否在启动的时候就解析规则，默认为true
  parse-on-start: true
  #全局重试次数，默认为0
  retry-count: 1
  #是否支持不同类型的加载方式混用，默认为false
  support-multiple-type: false
  #全局默认节点执行器
  node-executor-class: com.yomahub.liteflow.flow.executor.DefaultNodeExecutor
  #是否打印执行中过程中的日志，默认为true
  print-execution-log: true
  #是否开启本地文件监听，默认为false
  enable-monitor-file: false
  #简易监控配置选项
  monitor:
    #监控是否开启，默认不开启
    enable-log: false
    #监控队列存储大小，默认值为200
    queue-limit: 200
    #监控一开始延迟多少执行，默认值为300000毫秒，也就是5分钟
    delay: 300000
    #监控日志打印每过多少时间执行一次，默认值为300000毫秒，也就是5分钟
    period: 300000