package com.coral.base.common;

import com.coral.base.common.json.JsonUtil;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author huss
 * @version 1.0
 * @className XmlUtilTest
 * @description xml 工具类测试
 * @date 2021/6/11 10:40
 */
public class XmlUtilTest {

    @Test
    @DisplayName("解析xml4")
    public void parseXml4() {
        String xml = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\">\n" +
                "   <soapenv:Body>\n" +
                "      <zys:CallInterfaceResponse xmlns:zys=\"http://www.zysoft.com.cn/\">\n" +
                "         <zys:payload><![CDATA[<?xml version=\"1.0\" encoding=\"UTF-8\"?><root><contents><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[0.01]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000576]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[嗜碱性粒细胞计数]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[0--0.1]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[10^9/L]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[3.57]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[2508]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[白细胞]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[4.8--14.6]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[10^9/L]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[48.12]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[2952]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[中性粒细胞比率]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[9--57]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[%]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[42.30]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[2950]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[淋巴细胞比率]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[31--81]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[%]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[9.17]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000782]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[单核细胞比率]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[2--13]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[%]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[0.23]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[4002]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[嗜酸性粒细胞比率]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[1--10]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[%]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[0.18]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[4003]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[嗜碱性粒细胞比率]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[0--1]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[%]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[1.72]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[2954]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[中性粒细胞计数]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[0.8--6.4]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[10^9/L]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[1.51]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[2955]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[淋巴细胞计数]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[2.5--9]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[10^9/L]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[0.01]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000661]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[嗜酸性粒细胞计数]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[0.07--1.02]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[10^9/L]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[4.46]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[2495]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[红细胞]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[4--5.5]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[10^12/L]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[132]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000719]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[血红蛋白]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[97--141]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[g/L]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[38.40]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000715]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[红细胞压积]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[30--41]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[%]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[0.33]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[0101008]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[单核细胞计数]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[0.14--1.00]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[10^9/L]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[86.1]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000865]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[红细胞平均体积]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[72--86]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[fL]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[29.6]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000776]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[平均血红蛋白量]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[24--30]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[pg]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[344]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000777]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[平均血红蛋白浓度]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[310--355]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[g/L]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[39.0]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[0101023]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[红细胞分布宽度标准差]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[37--54]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[fL]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[147]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000829]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[血小板]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[190--579]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[10^9/L]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[13.8]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000824]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[血小板分布宽度]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[1--18]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[fL]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[0.121]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[2957]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[血小板压积]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[0.1--0.28]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[%]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[8.2]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[M000000783]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[平均血小板体积]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[6--13]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[fL]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content><content><EXAMINE_DATE>2023-08-15 08:15:22.0</EXAMINE_DATE><AGE_UNIT>岁</AGE_UNIT><EXAMINE_CODE>393653</EXAMINE_CODE><ABNORMAL_VALUE_TYPE/><EXAMINE_SUBITEMS_VALUE><![CDATA[13.7]]]]>><![CDATA[</EXAMINE_SUBITEMS_VALUE><DOCTOR_CODE_NOW>kyq</DOCTOR_CODE_NOW><PATIENT_TYPE>1</PATIENT_TYPE><PATIENT_SEX>2</PATIENT_SEX><DISEASE_NAME>急性鼻咽炎［感冒］</DISEASE_NAME><DOCTOR_NAME_NOW>寇玉芹</DOCTOR_NAME_NOW><PATIENT_NAME>郝书宁</PATIENT_NAME><EXAMINE_SUBITEMS_CODE><![CDATA[2590]]]]>><![CDATA[</EXAMINE_SUBITEMS_CODE><CRISISVAL_VALUE/><BARCODE_NO>6308156889</BARCODE_NO><AGE>0.8333</AGE><OUT_PATIENT_NO>6760564004</OUT_PATIENT_NO><DISEASE_ICD>J00.x00</DISEASE_ICD><DEPT_NAME_NOW>检验科</DEPT_NAME_NOW><EXAMINE_SUBITEMS_NAME><![CDATA[红细胞分布宽度]]]]>><![CDATA[</EXAMINE_SUBITEMS_NAME><NORMAL_VALUE><![CDATA[11.6--14.8]]]]>><![CDATA[</NORMAL_VALUE><ADMISSION_NUMBER/><BILL_NO>dcf40638-e4b5-48c6-a748-dd68c0d12bd1</BILL_NO><OUT_PATIENT_NUMBER>6760564</OUT_PATIENT_NUMBER><PATIENT_ID>0001302060</PATIENT_ID><DEPT_CODE_NOW>60200</DEPT_CODE_NOW><EXAMINE_TIME>2023-08-15 08:13:09.0</EXAMINE_TIME><HOSPITAL_PIPELINE_NO/><EXAMINE_SUBITEMS_UNIT><![CDATA[%]]]]>><![CDATA[</EXAMINE_SUBITEMS_UNIT></content></contents></root>]]></zys:payload>\n" +
                "      </zys:CallInterfaceResponse>\n" +
                "   </soapenv:Body>\n" +
                "</soapenv:Envelope>";

        XmlUtil.XmlParseConfig xmlParseConfig = new XmlUtil.XmlParseConfig(true, Contents.class);
        Map<String, String> xmlMap = new HashMap<>(4);
        xmlMap.put("soapenv", "http://schemas.xmlsoap.org/soap/envelope/");
        xmlMap.put("zys", "http://www.zysoft.com.cn/");
        xmlParseConfig.setXpathNamespaces(xmlMap);
        xmlParseConfig.setXpathExpression("//zys:payload");
        xmlParseConfig.setXpathValParse(true);
        xmlParseConfig.setXpathValExpression("//contents");
        List<Contents> responses = XmlUtil.parseXml(xml, xmlParseConfig);
        System.out.println(responses);
        System.out.println(JsonUtil.toJson(responses));
    }


    @Data
    @Getter
    @Setter
    static class Contents {
        private List<Content> content;
    }

    @Data
    @Getter
    @Setter
    static class Content {
        @JsonProperty("EXAMINE_DATE")
        private String examineDate;
        @JsonProperty("AGE_UNIT")
        private String ageUnit;
    }

    @Test
    @DisplayName("创建xml测试")
    public void createXml() {
        XmlBean xmlBean = XmlBean.builder()
                .name("test1")
                .age(12D)
                .sex(true)
                .list(Arrays.asList("1", "2", "3", "4", "6"))
                .items(
                        Arrays.asList(
                                new XmlItemBean("122"),
                                new XmlItemBean("23331"),
                                new XmlItemBean("432"),
                                new XmlItemBean("12")
                        )
                )
                .build();

        String xml = XmlUtil.createXml(xmlBean, "Response", true, true);
        System.out.println(xml);
    }

    @Test
    @DisplayName("解析xml测试")
    public void parseXml() throws IOException {
        String path = "D:\\projects\\mine\\coral-cloud\\coral-base\\coral-common\\src\\test\\java\\com\\coral\\base\\common\\res.xml";
        System.out.println(Paths.get(path));
        List<String> lines = FileUtil.readFile(new FileInputStream(Paths.get(path).toFile()), "gb2312");
        String xml = String.join("", lines);
        System.out.println("xml:" + xml);
        XmlUtil.XmlParseConfig xmlParseConfig = new XmlUtil.XmlParseConfig(false, null, Map.class);
        List<Map> list = XmlUtil.parseXml(xml, xmlParseConfig);
        System.out.println("-------------------------------------------------------");
        System.out.println(list);

    }

    @Test
    @DisplayName("解析xml测试2")
    public void parseXml2() throws IOException {
        String xml = "<xml>\n" +
                "  <result>\n" +
                "    <code>1000</code>\n" +
                "    <msg>操作成功</msg>\n" +
                "  </result>\n" +
                "  <dataSet class=\"com.alpha.commons.core.pojo.HospitalizedPatientInfoNew1\">\n" +
                "    <id>3</id>\n" +
                "    <patientName>吕瑶瑶</patientName>\n" +
                "    <sex>2</sex>\n" +
                "    <age>3岁4月</age>\n" +
                "    <birthday>2018-12-21 00:00:00</birthday>\n" +
                "    <nation>1</nation>\n" +
                "    <nationality>1</nationality>\n" +
                "    <outPatientNo>8800000090</outPatientNo>\n" +
                "    <contactPhone>13655287268</contactPhone>\n" +
                "    <contactName>何处</contactName>\n" +
                "    <contactAddr>黑龙江省哈尔滨市道里区新阳路街道过去陪不了我</contactAddr>\n" +
                "    <relationship>2</relationship>\n" +
                "    <patientCertiNo></patientCertiNo>\n" +
                "    <homePlace>10</homePlace>\n" +
                "    <signUrl>dat=</signUrl>\n" +
                "    <mailingAddress>河北省石家庄市长安区远处自有归处</mailingAddress>\n" +
                "    <nativePlace>8375</nativePlace>\n" +
                "    <xzz>黑龙江省哈尔滨市道里区新阳路街道@过去陪不了我</xzz>\n" +
                "    <patientType>45</patientType>\n" +
                "    <noticeId>88000009020181221</noticeId>\n" +
                "    <rStatus>0</rStatus>\n" +
                "  </dataSet>\n" +
                "</xml>";
        System.out.println("xml:" + xml);
        XmlUtil.XmlParseConfig xmlParseConfig = new XmlUtil.XmlParseConfig(true, null, Result2.class);
        List<Result2> list = XmlUtil.parseXml(xml, xmlParseConfig);
        System.out.println("-------------------------------------------------------");
        System.out.println(list.get(0));

    }

    @Test
    @DisplayName("解析xml测试3")
    public void parseXml3() {
        String xml = " <request>\n" +
                "                <businessType>ywz</businessType>\n" +
                "                <function>2wwwe2</function>\n" +
                "                <params>333</params>\n" +
                "                <age>23</age>\n" +
                "                <money>5000.26</money>\n" +
                "                <isMale>true</isMale>\n" +
                "                <list>1,2</list>\n" +
                "                <list>2</list>\n" +
                "                <list>4</list>\n" +
                "                <children>\n" +
                "                    <no>11</no>\n" +
                "                    <name>11_na</name>\n" +
                "                </children>\n" +
                "                <children>\n" +
                "                    <no>22</no>\n" +
                "                    <name>22_na</name>\n" +
                "                </children>\n" +
                "                <map>\n" +
                "                    <entry>\n" +
                "                        <key>11</key>\n" +
                "                        <value>11_val</value>\n" +
                "                    </entry>\n" +
                "                    <entry>\n" +
                "                        <key>22</key>\n" +
                "                        <value>22_val</value>\n" +
                "                    </entry>\n" +
                "                </map>\n" +
                "                <son>\n" +
                "                    <no>33</no>\n" +
                "                    <name>33_name</name>\n" +
                "                </son>\n" +
                "            </request>";
        System.out.println("xml:" + xml);
        XmlUtil.XmlParseConfig xmlParseConfig = new XmlUtil.XmlParseConfig(true, Arrays.asList("children", "list"), Map.class);
        List<Map> list = XmlUtil.parseXml(xml, xmlParseConfig);
        System.out.println("-------------------------------------------------------");
        System.out.println(list.get(0));
    }

    @Data
    private static class Result2 {

        private Map<String, Object> dataSet;
    }

    @Data
    @Builder
    private static class XmlBean {

        private String name;

        private Double age;

        private Boolean sex;

        private List<String> list;

        private List<XmlItemBean> items;

    }

    @AllArgsConstructor
    @Data
    private static class XmlItemBean {
        private String value;
    }
}
