info:
  author: huss
  date: 2023年12月28号
  remark: spring-graphql 测试
  my-server-name: spring-graphql


#spring
spring:
  application:
    name: ${info.my-server-name}
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true