# 数据源配置
--- !!seq
- !database
  key: zhyx_test
  hostname: '192.168.29.188'
  port: '3306'
  username: 'zhyx'
  password: 'zhyx'
- !database
  key: zhyx_dev
  hostname: '192.168.29.66'
  port: '3306'
  username: 'zhyx'
  password: 'zhyx'

